[package]
name = "framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program-test = "1.17.3"
solana-program = "1.17.3"
solana-logger = "1.17.3"
solana-sdk = "1.17.3"
spl-token = "3.3.0"
chall = { path ="./chall/" }
sol-ctf-framework = { git = "https://github.com/otter-sec/sol-ctf-framework", branch="rewrite-v2" }
threadpool = "1.8.1"
